---
title: "F1 Project"
author: "Hailey, Finn, Mia, Caili"
date: "2025-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
library(dplyr)

results <- read_excel("Results.xlsx")

results

weather <- read_excel("Weather.xlsx")

weather
```

```{r}
results <- results %>%
  select(TeamName, FullName, Position, GridPosition, Status, Points, RoundNumber, EventName) %>%
  mutate(
    Position = as.integer(Position),
    GridPosition = as.integer(GridPosition),
    Points = as.integer(Points),
    RoundNumber = as.integer(RoundNumber)
  ) %>%
  rename (
    DriverName = FullName,
    Result = Position,
    QualiPosition = GridPosition
  )
  

results
```
```{r}
weather <- weather %>%
  select(Rainfall, TrackTemp, RoundNumber, EventName) %>%
  mutate(RoundNumber = as.integer(RoundNumber)) %>%
  rename(Rain = Rainfall)

weather
```


**The below section breaks the weather dataframe into 2 parts: track temperature and rainy races. The average track temperature for each race & round number is found. The number of races that had more than 10 true's under rain was also found.**
```{r}
track_only <- weather %>%
  group_by(EventName, RoundNumber) %>%
  summarize(AvgTrackTemp = mean(TrackTemp, na.rm=T)) %>%
  arrange(desc(AvgTrackTemp))

track_only


rain_only <- weather %>%
  group_by(EventName, RoundNumber) %>%
  summarize(NumRain = sum(Rain)) %>%
  filter(NumRain >= 10)

rain_only
```
